#!/bin/bash
clear
while [ 1 ]
do
clear
disp1()
{

echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
return
}
disp()
{
tput cup 4 20
echo -e "\33[33m ************************** \33[0m"
tput cup 5 20
echo -e "\33[37m  Welcome to ADMINIX Project \33[0m"
tput cup 6 20
echo -e "\33[32m ************************** \33[0m"
return 
}
disp
tput cup 7 20
echo '--------------------------------------------------'
tput cup 8 20
echo '|  1. SYSTEM OPTIONS                             |'
tput cup 9 20
echo '|  2. SERVER OPTIONS                             |'
tput cup 10 20
echo '|  3. NETWORK OPTIONS                            |'
tput cup 11 20
echo '|  4. HARDWARE OPTIONS                           |'
tput cup 12 20
echo '|  5. OTHER OPTIONS                              |'
tput cup 13 20
echo '|  Q. Quit                                       |'  
tput cup 14 20
echo -e "\33[45m|  Enter your choice:           |\33[0m"
tput cup 15 20
echo '--------------------------------------------------'
tput cup 14 41 
read  choice
case $choice in
	
1) 	sh /harshit/system/system
        disp1
	read;;

2) 	sh /harshit/server/server
        disp1  
	read;;

3)      sh /harshit/network/network
        disp1
        read;;
4)	sh /harshit/hardware/hardware
        disp1
	read;;

5)	clear
        sh /harshit/other/fsh
        tput cup 30 20
        disp1
	read ;;

Q)

	clear 
		exit;;

q)
	clear
	        exit;;

*)
echo -e "\33[35m  IMPROPER CHOICE \33[0m"
echo -e "\33[41m  Press Enter to Continue...! \33[0m"
read id;;
esac
done

